name: Wakatime README

on:
  workflow_dispatch:
  schedule:
    # Runs at 5PM (UTC) everyday
    - cron: "0 17 * * *"
    
jobs:
  update-readme:
    name: Update the README content
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: README synced
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TITLE: true
